### ISSUE TITLE
Crash in examples/exploremap.py

### ISSUE THREAD

**Issue by Jimmio92** [lillian-lemmer/hypatia-engine#8] opened 2015-02-15 20:33 UTC
Crashes on Windows 7 Ultimate x64 (**EDIT**: And lubuntu 14.10 x64) when approaching non-walkable tile (it seems). Could be a missing check to see if you can move into a location or not?

```
Traceback (most recent call last):
  File "exploremap.py", line 81, in <module>
    game_blueprint.start_loop()
  File "../engine\game.py", line 184, in start_loop
    self.render()
  File "../engine\game.py", line 170, in render
    self.viewport.rect.topleft
  File "../engine\sprites.py", line 316, in blit
    parent_anchor_position = (position_on_screen[0] + frame_anchor[0],
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Python 2.7, Newest pygame, newest pyganim, newest PIL.

**Comment by lillian-lemmer** [comment] 2015-02-16 00:06
I'm guessing frame_anchor is empty? Something like that. I'm testing out stuff on a VM now, since it's working on my computer (I tried downloading new and running).

**Comment by lillian-lemmer** [comment] 2015-02-16 18:30
If you download the latest edition, do you still have this issue?
 
I'm having a hard time reproducing this issue.

**Comment by lillian-lemmer** [comment] 2015-02-18 01:52
Tested in Ubuntu 14.04.1 LTS on 2015-02-17 with https://github.com/lillian-lemmer/hypatia-engine/commit/7aaee83027c648267bec0e791ebaf71bd5a7761b

Works for me?

**Comment by lillian-lemmer** [comment] 2015-02-18 04:21
Also working in Elementary OS. If it works in Windows I'm going to assume the issue has been fixed and close the issue.

**Comment by lillian-lemmer** [comment] 2015-02-18 08:18
Also tested in Windows 7 x64. Marking issue as resolved.

**Closed by lillian-lemmer** 2015-02-18 08:18 UTC
